spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    maxActive: 25
    maxIdle: 20
    minIdle: 10
    testOnBorrow: true
    validationQuery: SELECT 1

server.port: 8083


---

spring:
  profiles: test
  datasource:
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    username: "root"
    password: "root1"


---

spring:
  profiles: default
  datasource:
    url: "jdbc:mysql://localhost:3306/test2=true&characterEncoding=utf8&autoReconnect=true"
    username: "root"
    password: "root1"
